### ISSUE TITLE
segfault with SvmToolPosTagger

### ISSUE THREAD

**Issue by mesnard** [aymara/lima#84]
Segmentation fault during text analysis.

With version debug of lima from:
commit 60e84c33a1ccca1d702f9581db16d6af18ec74dd (HEAD -> master, origin/master, origin/HEAD)
Author: Gael de Chalendar <gael.de-chalendar@cea.fr>
Date:   Tue May 14 18:24:29 2019 +0200 (Correct fre POS training corpus)

and with changes from standard configuration in lima-lp-fre.xml (see conf.zip) :
        <item value="SvmToolPosTagger"/>
        <item value="bowDumper"/>

Command "analyzeText -l fre -d bow 0001.part.txt 0002.part.txt"
results in "Erreur de segmentation (core dumped)"

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - compiler: gcc (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
[0001.part.txt](https://github.com/aymara/lima/files/3182769/0001.part.txt)
[0002.part.txt](https://github.com/aymara/lima/files/3182771/0002.part.txt)

[conf.zip](https://github.com/aymara/lima/files/3182779/conf.zip)

**Comment by mesnard** [comment]
On Lima head commit 3504cc4ab69988b53085282ddbf836a8325c2ef7
(2019/07/16) command: 
analyzeText -l fre DEF_final_JAP_BD.2.txt
with standard configuration ends with Error:
================================
Analyzing 1/1 (100.00%) 'DEF_final_JAP_BD.2.txt' : LP::PosTagger : 2019-07-16T11:36:13.066 ERROR 0x55696d835c80 Error in SVMTagger result line: did not get 2 elements in '  ' 
 : LP::CoreClient : 2019-07-16T11:36:13.066 ERROR 0x55696d835c80 analysis failed : receive status 3 from pipeline. exit 
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

Catched LinguisticProcessingException: analysis failed : receive status 3 from pipeline. exit
terminate called after throwing an instance of 'Lima::LinguisticProcessing::LinguisticProcessingException'
  what():  analysis failed : receive status 3 from pipeline. exit
Abandon (core dumped)
================================
Text is 1 line of Japanese.
Same command with "viterbiPostagger-freq" in pipeline is OK

**Comment by mesnard** [comment]
I forgot to upload the japanese text:
[DEF_final_JAP_BD.2.txt](https://github.com/aymara/lima/files/3396521/DEF_final_JAP_BD.2.txt)

**Comment by benlabbe** [comment]
I also observed a similar bug recently. While inspecting the logs before the segfault, I clearly found that SVMTolPosTagger went to an error as soon as **3 \n were consecutive** in the document.

The PosTagger said a similar message : 
LP::PosTagger : 2019-10-15T11:36:13.066 ERROR 0x55696d835c80 **Error in SVMTagger result line: did not get 2 elements in ' '**

**Comment by kleag** [comment]
I confirm the crash with the following content:
```
Test


Test
```

**Comment by kleag** [comment]
This is corrected by commit 0edb2f4. I was not able to reproduce the problem with attached Japanese and French files though.

**Comment by benlabbe** [comment]
Correction OK.

**Comment by mesnard** [comment]
Error still occurs when analyzing document with japanese  characters  DEF_final_JAP_BD.2.txt
[DEF_final_JAP_BD.2.txt](https://github.com/aymara/lima/files/3754928/DEF_final_JAP_BD.2.txt)

analyzeText -l fre DEF_final_JAP_BD.2.txt
```
Analyzing 1/1 (100.00%) 'DEF_final_JAP_BD.2.txt' : LP::PosTagger : 2019-10-22T12:18:20.766 ERROR 0x5605ddbd9c80 Error in SVMTagger result line: did not get 2 elements in '  ' 
 : LP::CoreClient : 2019-10-22T12:18:20.766 ERROR 0x5605ddbd9c80 analysis failed : receive status 1 from pipeline. exit 
terminate called after throwing an instance of 'Lima::LinguisticProcessing::LinguisticProcessingException'
  what():  analysis failed : receive status 1 from pipeline. exit
Abandon (core dumped)
```
Error does not occur with document DEF_final_JAP_BD.3.txt
[DEF_final_JAP_BD.3.txt](https://github.com/aymara/lima/files/3754976/DEF_final_JAP_BD.3.txt)
where a kind of punctuation character (。) is removed from text.

Error still occurs with this minimal document:
[DEF_final_JAP_BD.4.txt](https://github.com/aymara/lima/files/3755025/DEF_final_JAP_BD.4.txt)
With command:
analyzeText -l fre -d bow DEF_final_JAP_BD.4.txt
And with minimal pipeline:
        <item value="flattokenizer"/>
        <item value="simpleWord"/>
        <item value="SvmToolPosTagger"/>
        <item value="bowDumper"/>

when SvmToolPosTagger is replaced by viterbiPostagger-freq, analyzer outputs an empty bow document but does not crash.

**Comment by mesnard** [comment]
With the following configuration:
[confLima.zip](https://github.com/aymara/lima/files/3755597/confLima.zip)

And the following coomand:
analyzeText -l fre -d bow DEF_final_JAP_BD.4.txt >& trace.txt

We obtain the folllowing trace:
[trace.txt](https://github.com/aymara/lima/files/3755587/trace.txt)

and the following graph before posTagging
[beforePosTag.dump.zip](https://github.com/aymara/lima/files/3755612/beforePosTag.dump.zip)

Note that there  is only 1node with an empty string.
It seems that AlternativesReader::readAlternatives  process imput text as an acronym and builds empty string.
